# Generated by Django 5.2.13 on 2026-04-10 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('started_at_us', models.BigIntegerField()),
                ('ended_at_us', models.BigIntegerField(blank=True, null=True)),
                ('source', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('risk_label', models.TextField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='RawFrame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_us', models.BigIntegerField()),
                ('gw', models.IntegerField()),
                ('gh', models.IntegerField()),
                ('battery_pct', models.IntegerField()),
                ('flags', models.IntegerField()),
                ('total_load', models.FloatField()),
                ('adc_blob', models.BinaryField()),
                ('session', models.ForeignKey(db_column='session_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='raw_frames', to='wbs.session')),
            ],
            options={
                'db_table': 'raw_frames',
                'indexes': [models.Index(fields=['session'], name='idx_frames_session')],
            },
        ),
        migrations.CreateModel(
            name='ComputedMetric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_us', models.BigIntegerField()),
                ('metric_name', models.TextField()),
                ('metric_value', models.FloatField()),
                ('unit', models.TextField(blank=True, null=True)),
                ('session', models.ForeignKey(db_column='session_id', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='computed_metrics', to='wbs.session')),
            ],
            options={
                'db_table': 'computed_metrics',
                'indexes': [models.Index(fields=['session'], name='idx_metrics_session')],
            },
        ),
    ]
