# Generated by Django 5.2.13 on 2026-04-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationProfile',
            fields=[
                ('calibration_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=128)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calibration_profiles',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('firmware_version', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(default='clinical_summary', max_length=64)),
                ('pdf_file_path', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('clinician_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='calibration_profile',
            field=models.ForeignKey(blank=True, db_column='calibration_profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='wbs.calibrationprofile'),
        ),
        migrations.AddField(
            model_name='calibrationprofile',
            name='device',
            field=models.ForeignKey(db_column='device_id', on_delete=django.db.models.deletion.CASCADE, related_name='calibration_profiles', to='wbs.device'),
        ),
        migrations.AddField(
            model_name='session',
            name='device',
            field=models.ForeignKey(blank=True, db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='wbs.device'),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('annotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='wbs.session')),
                ('patient', models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='wbs.patient')),
            ],
            options={
                'db_table': 'annotations',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='wbs.patient'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['patient'], name='idx_sessions_patient'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['device'], name='idx_sessions_device'),
        ),
        migrations.AddField(
            model_name='report',
            name='session',
            field=models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='wbs.session'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='report',
            field=models.ForeignKey(blank=True, db_column='report_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='wbs.report'),
        ),
        migrations.AlterUniqueTogether(
            name='calibrationprofile',
            unique_together={('device', 'profile_name', 'version')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['session'], name='idx_reports_session'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['patient'], name='idx_annotations_patient'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['session'], name='idx_annotations_session'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['report'], name='idx_annotations_report'),
        ),
    ]
