# Generated by Django 4.2.16 on 2026-04-10 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wbs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wbs', '0002_calibrationprofile_device_patient_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicianUiPreference',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_layout', models.JSONField(blank=True, default=wbs.models.default_sensor_layout)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinician_ui_preferences',
            },
        ),
    ]
